### ISSUE TITLE
devise ssl redirection eats up flash messages in production only

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape-chef#10]
When redirecting http -> https the flash messages (e.g. "You must sign up or sign in to continue" get eaten by the redirect. Probably needs fixing in devise with a bit of flash.keep or similar.

Actually, it's been fixed in rails itself. Expect the fix in 3.3. https://github.com/rails/rails/pull/4429

**Comment by nikolai-b** [comment]
We have the new rails version so I'm closing this.
