### ISSUE TITLE
Support Ubuntu 14.04 and 12.04

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape-chef#24]
This is a wider issue than just #18 !

- [x] apache cookbook
- [x] postgresql and postgis versions
- [x] passenger won't compile on 1404
- [x] rgeo doesn't gain geos support
- [x] db migration fails
- [x] apache config dirs have changed
- [ ] apache 2.4 needs a different line for passenger (see comment)
- [ ] apache 2.4 SSL configuration file not working

**Comment by nikolai-b** [comment]
Using https://github.com/chef-cookbooks/passenger_apache2 so closing
