### ISSUE TITLE
Passenger pre-start doesn't appear to work

### ISSUE THREAD

**Issue by gravitystorm** [cyclestreets/cyclescape-chef#6]
I've found first-page load after a deploy takes quite a while, indicating that passenger pre-start may not be working.

The bug in passenger was fixed a while ago, so we should check our configuration.

**Comment by nikolai-b** [comment]
I think this is fixed with https://github.com/cyclestreets/cyclescape-chef/commit/980e1f5bc9d1c9032c36da7db103f3c3877a1307
